version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: reservation_purchase_database
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password
    networks:
      - reservation_purchase

networks:
  reservation_purchase: