spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: ${MYSQL_DATABASE_URL}
        username: ${MYSQL_USER_NAME}
        password: ${MYSQL_USER_PASSWORD}
    jpa:
        properties:
            hibernate:
                show_sql: false
                dialect: org.hibernate.dialect.MySQL8Dialect
    cache:
        type: redis
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
    level:
        org:
            springframework:
                web: INFO
jwt:
    secret-key: ${JWT_SECRET_KEY}
    accessToken.expired-time-ms: ${JWT_EXPIRED_TIME_MS}

file:
    local:
        upload:
            path: ${FILE_SAVE_PATH}

email:
    id: ${EMAIL_ID}
    pw: ${EMAIL_PASSWORD}