server:
    port: 8083

spring:
    config:
        activate:
            on-profile: dev
    application:
        name: apigateway_service
    cloud:
        gateway:
            default-filters:
                - name: LoggingFilter
                  # 로깅 설정값 추가 가능

            routes: # 8083 api gateway 로 오는 해당 경로는 uri + Path 로 넘기겠다.
                # user_service
                - id: user_service
                  uri: http://localhost:8080/
                  predicates:
                      - Path=/v1/members/**
                - id: auth_service
                  uri: http://localhost:8080/
                  predicates:
                      - Path=/v1/auth/**

                # activity_service
                - id: article_service
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/v1/articles/**
                - id: comment_service
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/v1/comments/**
                - id: follow_service
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/v1/follows/**

                # newsfeed_service
                - id: newsfeed_service
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/v1/newsfeeds/**

